CREATE TABLE country (ID bigint PRIMARY KEY, NAME varchar(255), ISO_CODE varchar(3));
CREATE TABLE region(ID bigint PRIMARY KEY , NAME varchar(225), COUNTRY_ID_FK bigint, FOREIGN KEY(COUNTRY_ID_FK) REFERENCES country(ID));
CREATE TABLE appellation(ID bigint PRIMARY KEY , NAME varchar(225), REGION_ID_FK bigint, COLOUR varchar(20), FOREIGN KEY(REGION_ID_FK) REFERENCES region(ID));
CREATE TABLE detail(ID bigint PRIMARY KEY, COUNTRY_ID_FK bigint NULL,  REGION_ID_FK bigint NULL,  APPELLATION_ID_FK bigint NULL,  TYPE varchar(20), MAP_READY BOOLEAN default false,
                    FOREIGN KEY(COUNTRY_ID_FK) REFERENCES country(ID),
                    FOREIGN KEY(REGION_ID_FK) REFERENCES region(ID),
                    FOREIGN KEY(APPELLATION_ID_FK) REFERENCES appellation(ID));

INSERT INTO country(ID, NAME, ISO_CODE) values (1,'FRANCE','FR');
INSERT INTO region (ID, NAME, COUNTRY_ID_FK) VALUES (1,'BORDELAIS', 1);
INSERT INTO appellation (ID, NAME, REGION_ID_FK, COLOUR) VALUES (1, 'MEDOC', 1, 1);
INSERT INTO detail(ID, COUNTRY_ID_FK, REGION_ID_FK, APPELLATION_ID_FK, TYPE, MAP_READY) VALUES (1, 1, NULL, NULL, 0, true);
INSERT INTO detail(ID, COUNTRY_ID_FK, REGION_ID_FK, APPELLATION_ID_FK, TYPE, MAP_READY) VALUES (2, 1, 1, NULL, 1, false);
INSERT INTO detail(ID, COUNTRY_ID_FK, REGION_ID_FK, APPELLATION_ID_FK, TYPE, MAP_READY) VALUES (3, 1, 1, 1, 2, true);