name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 15.236.112.83 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ec2-user@15.236.112.83 << 'EOF'
            cd /home/ec2-user/vinocarto
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF